#!/usr/bin/env ruby

require 'json'

path = File.expand_path('~/.config/chromium/Local State')

content = JSON.parse(File.read(path))
unless content.key?('browser')
  content['browser'] = {}
end
experiments = content['browser']['enabled_labs_experiments'] || []
%w(
  smooth-scrolling@2
  fingerprinting-canvas-image-data-noise
  fingerprinting-canvas-measuretext-noise
  fingerprinting-client-rects-noise
  username-first-flow@1
  enable-show-autofill-signatures
  allow-insecure-localhost
  omnibox-tab-switch-suggestions@2
  omnibox-autocomplete-titles@2
  omnibox-drive-suggestions@6
  prefetch-privacy-changes@1
).each do |exp|
  unless experiments.include?(exp)
    experiments << exp
  end
end
content['browser']['enabled_labs_experiments'] = experiments
File.open(path, 'w') do |f|
  f << JSON.dump(content)
end
