#!/usr/bin/env ruby

$: << File.join(File.expand_path(__FILE__), '../../lib/ruby')

require 'chromium_configurator'

path = ARGV.shift || File.expand_path('~/.config')

ChromiumConfigurator.new(path).configure
