#!/bin/sh

AGENTRC="$HOME/.ssh/agentrc"

unset SSH_AGENT_PID SSH_AUTH_SOCK

if [ -f "$AGENTRC" ]; then
	. "$AGENTRC"
	if ! kill -0 $SSH_AGENT_PID; then
		unset SSH_AGENT_PID SSH_AUTH_SOCK
	fi
fi

if [ -z "$SSH_AGENT_PID" ]; then
	ssh-agent > "$AGENTRC"
	. "$AGENTRC"
	ssh-add
fi	
