if test -d "$HOME/bin"; then
  export PATH="$HOME/bin:$PATH"
fi

if test -f /etc/debian_version; then
  export DEBEMAIL=oleg@bsdpower.com
  export DEBFULLNAME='Oleg Pudeyev'
fi

if test -d "$HOME/.rbenv/bin"; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

export PATH=$PATH:~/.local/bin

# Recent linuxes botch date format, get the old one back
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

export FILTER_BRANCH_SQUELCH_WARNING=1

export PATH=~/.local/share/gem/ruby/3.0.0/bin:$PATH
