_maybe_add_to_path() {
  dir="$1"
  if test -d "$dir"; then
    export PATH="$dir:$PATH"
  fi
}

_maybe_add_to_path "$HOME/bin"
_maybe_add_to_path "$HOME/.local/bin"

if test -f /etc/debian_version; then
  export DEBEMAIL=oleg@bsdpower.com
  export DEBFULLNAME='Oleg Pudeyev'
fi

_maybe_add_to_path "$HOME/.rbenv/bin"
_maybe_add_to_path "$HOME/.local/share/gem/ruby/3.0.0/bin"

# Recent linuxes botch date format, get the old one back
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

export FILTER_BRANCH_SQUELCH_WARNING=1

# Prevent bundler from installing versions of itself and re-execing them.
# For pre-2.5 bundlers (2.3, 2.4).
export BUNDLER_VERSION=99
