if test -d "$HOME/bin"; then
  export PATH="$HOME/bin:$PATH"
fi

if test -f /etc/debian_version; then
  export DEBEMAIL=oleg@bsdpower.com
  export DEBFULLNAME='Oleg Pudeyev'
fi

if test -d "$HOME/.rbenv/bin"; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

if test -d "$HOME/bin"; then
  export PATH="$HOME/bin:$PATH"
fi
export PATH=$PATH:~/.local/bin
