#!/usr/bin/env ruby

require 'optparse'
require_relative '../../../lib/ruby/global_helpers'
require_relative '../../../lib/ruby/fs_helpers'
require_relative '../lib/helpers'
require_relative '../lib/browsers'
require_relative '../lib/context'
require_relative '../lib/builder'

overrides_path = File.join(File.dirname(__FILE__), '../lib/overrides')
if File.exist?(overrides_path)
  FsHelpers.entries_in_path(overrides_path).each do |entry|
    path = File.join(overrides_path, entry)
    load(path)
  end
end

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: build [-cNr] [-d path]"

  opts.on("-c", "--check", "Check system") do
    options[:check] = true
  end

  opts.on("-d", "--dest=PATH", "Write resulting files into this directory (default: $XDG_CONFIG_HOME/.openbox or if not set, ~/.config/openbox)") do |v|
    options[:dest_path] = v
  end

  opts.on("-N", "--skip-network", "Do not perform network operations") do
    options[:network] = false
  end

  opts.on("-r", "--reload", "Reload running openbox") do
    options[:reload] = true
  end

  opts.on("-P", "--pretty", "Prettify generated XML") do
    options[:pretty] = true
  end
end.parse!

builder_cls = begin
  LocalBuilder
rescue NameError
  Builder
end
builder = builder_cls.new(**options)
builder.build

if options[:reload]
  builder.reload
end
