#!/bin/sh

set -e

apt-get install curl

curl https://raw.githubusercontent.com/p/pubfiles/master/script/configure-apt-no-recommends | sh

apt-get install git python-is-python3 console-setup console-setup-linux \
  ruby ruby-childprocess openssh-server

mkdir -p /usr/libexec/pubfiles

curl -o /usr/libexec/pubfiles/connect-wireless \
  https://raw.githubusercontent.com/p/pubfiles/master/script/connect-wireless

chmod 0555 /usr/libexec/pubfiles/connect-wireless
