#!/bin/sh

set -e

apt-get install curl

curl https://raw.githubusercontent.com/p/pubfiles/master/script/configure-apt-no-recommends | sh

apt-get install git python-is-python3 console-setup console-setup-linux

#mkdir -p $HOME/apps

#git clone https://github.com/p/pubfiles $HOME/apps
