#!/bin/sh

apt-get install curl

curl https://raw.githubusercontent.com/p/pubfiles/master/script/configure-apt-no-recommends | sh

apt-get install git

mkdir -p $HOME/apps

git clone https://github.com/p/pubfiles $HOME/apps
