#!/bin/sh

set -e

for group in cdrom floppy audio dip video plugdev netdev bluetooth docker; do
  if groupmod $group; then
    groups="$groups,$group"
  fi
done
if id w >/dev/null 2>&1; then
  usermod -s /bin/zsh -G $groups w
else
  useradd -m -s /bin/zsh -u 2515 -G $groups w
fi
