#!/bin/sh

set -e

groups=

for group in files; do
  if groupmod $group; then
    groups="$groups,$group"
  fi
done
groups=`echo "$groups" |sed -e s/^,//`
if id readall >/dev/null 2>&1; then
  if test -n "$groups"; then
    groups="-aG $groups"
  fi
  usermod -s /bin/zsh $groups readall
else
  if test -n "$groups"; then
    groups="-G $groups"
  fi
  useradd -m -s /bin/zsh -u 2225 $groups readall
fi

# Normally the home directory would be created by useradd above, but if
# /home was completely removed then user may remain without a homedir.
if ! test -d /home/readall; then
  mkdir /home/readall
  chown readall:readall /home/readall
fi
