#!/bin/sh

set -e

groups=
for group in cdrom floppy audio dip video plugdev netdev bluetooth docker; do
  if groupmod $group; then
    if test -n "$groups"; then
      groups="$groups,$group"
    else
      groups="$group"
    fi
  fi
done
if id w >/dev/null 2>&1; then
  usermod -s /bin/zsh -G $groups w
else
  useradd -m -s /bin/zsh -u 2515 -G $groups w
fi
