#!/bin/sh

set -e

groupmod wheel || groupadd -g 2500 wheel
groups=wheel
for group in cdrom floppy audio dip video plugdev netdev bluetooth docker; do
  if groupmod $group; then
    groups="$groups,$group"
  fi
done
useradd -m -s /bin/zsh -u 2501 -G $groups me
