#!/bin/sh

set -e

groupmod wheel || groupadd -g 2500 wheel
groupmod power || groupadd -g 2590 power
groups=wheel,power
# dialout: serial port access
# adm: read /var/log/messages
for group in input cdrom floppy audio dip video adm \
	plugdev netdev bluetooth docker dialout \
	br-acc br-sandbox; do
  if groupmod $group; then
    groups="$groups,$group"
  fi
done
if id me >/dev/null 2>&1; then
  usermod -s /bin/zsh -aG $groups me
else
  useradd -m -s /bin/zsh -u 2501 -G $groups me
fi

if test -d /etc/sudoers.d; then
  install -m 444 `dirname $0`/../config/sudoers.d/power-mgmt /etc/sudoers.d
fi

if which bundle >/dev/null 2>&1; then
  bundle config set --global path '~/.cache/vendor/bundle'
fi

for dir in .mozilla .waterfox .config/chromium; do
  su - me -c "mkdir -p $dir && chmod 0000 $dir"
done

# Normally the home directory would be created by useradd above, but if
# /home was completely removed then user may remain without a homedir.
if ! test -d /home/me; then
  mkdir /home/me
  chown me:me /home/me
fi
