#!/usr/bin/env ruby

require_relative '../lib/ruby/format_helpers'
require 'time'
require 'rugged'

class SmartInfo
  def initialize(text)
    text.split("\n").each do |line|
      case line
      when /\ALocal Time is:(.+)/
        @time = Time.parse($1)
      when /\Aread:/
        values = line.split(/\s+/)
        @read_corrected_fast = Integer(values[1])
        @read_corrected_delayed = Integer(values[2])
        @rereads = Integer(values[3])
        @read_corrected = Integer(values[4])
        @read_correction_invocations = Integer(values[5])
        @read_bytes_processed = (Float(values[6]) * 10**9).to_i
        @read_uncorrected = Integer(values[7])
      when /\Awrite:/
        values = line.split(/\s+/)
        @write_corrected_fast = Integer(values[1])
        @write_corrected_delayed = Integer(values[2])
        @rewrites = Integer(values[3])
        @write_corrected = Integer(values[4])
        @write_correction_invocations = Integer(values[5])
        @write_bytes_processed = (Float(values[6]) * 10**9).to_i
        @write_uncorrected = Integer(values[7])
      when /\Averify:/
        values = line.split(/\s+/)
        @verify_corrected_fast = Integer(values[1])
        @verify_corrected_delayed = Integer(values[2])
        @reverifys = Integer(values[3])
        @verify_corrected = Integer(values[4])
        @verify_correction_invocations = Integer(values[5])
        @verify_bytes_processed = (Float(values[6]) * 10**9).to_i
        @verify_uncorrected = Integer(values[7])
      end
    end
  end

  attr_reader :time
  attr_reader :read_corrected_fast, :read_corrected_delayed,
    :rereads, :read_corrected, :read_correction_invocations,
    :read_bytes_processed, :read_uncorrected
  attr_reader :write_corrected_fast, :write_corrected_delayed,
    :rewrites, :write_corrected, :write_correction_invocations,
    :write_bytes_processed, :write_uncorrected
  attr_reader :verify_corrected_fast, :verify_corrected_delayed,
    :reverifys, :verify_corrected, :verify_correction_invocations,
    :verify_bytes_processed, :verify_uncorrected
end

repo = Rugged::Repository.new('.')

ARGV.each do |file_path|
  puts file_path
  walker = Rugged::Walker.new(repo)
  walker.push(repo.head.target.oid)
  history = []
  walker.each do |commit|
    commit.diff.each_delta do |delta|
      history.push(commit.oid) if delta.new_file[:path] == file_path
    end
  end

  prev = nil
  history.each do |oid|
    blob = repo.blob_at(oid, file_path)
    #p blob.methods-Object.methods
    info = SmartInfo.new(blob.text)
    if prev
      puts "At #{prev.time}, for previous #{friendly_time(prev.time - info.time)}:"
      puts "#{friendly_size(prev.read_bytes_processed - info.read_bytes_processed)} read"
      puts "#{prev.read_correction_invocations - info.read_correction_invocations} read corrections"
      puts "#{friendly_size(prev.write_bytes_processed - info.write_bytes_processed)} written"
      puts "#{prev.write_correction_invocations - info.write_correction_invocations} write corrections"
      puts "#{friendly_size(prev.verify_bytes_processed - info.verify_bytes_processed)} verified"
      puts "#{prev.verify_correction_invocations - info.verify_correction_invocations} verify corrections"
      puts

      #p info
    end
    prev = info
  end
end
