#!/usr/bin/env ruby

require_relative '../lib/ruby/format_helpers'
require_relative '../lib/ruby/disk/smart_info'
require 'time'
require 'rugged'

repo = Rugged::Repository.new('.')

ARGV.each do |file_path|
  puts file_path
  walker = Rugged::Walker.new(repo)
  walker.push(repo.head.target.oid)
  history = []
  walker.each do |commit|
    commit.diff.each_delta do |delta|
      history.push(commit.oid) if delta.new_file[:path] == file_path
    end
  end

  prev = nil
  history.each do |oid|
    blob = repo.blob_at(oid, file_path)
    #p blob.methods-Object.methods
    info = SmartInfo.new(blob.text)
    if prev
      puts "At #{prev.time}, for previous #{friendly_time(prev.time - info.time)}:"
      puts "#{friendly_size(prev.read_bytes_processed - info.read_bytes_processed)} read"
      puts "#{prev.read_correction_invocations - info.read_correction_invocations} read corrections"
      puts "#{friendly_size(prev.write_bytes_processed - info.write_bytes_processed)} written"
      puts "#{prev.write_correction_invocations - info.write_correction_invocations} write corrections"
      puts "#{friendly_size(prev.verify_bytes_processed - info.verify_bytes_processed)} verified"
      puts "#{prev.verify_correction_invocations - info.verify_correction_invocations} verify corrections"
      puts

      #p info
    end
    prev = info
  end
end
