#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo sh -x "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

if ! grep -q '^spindown_time = 255' /etc/hdparm.conf; then
  sed -i -e s/'^spindown_time =/#spindown_time =/' /etc/hdparm.conf
  echo spindown_time = 255 |tee -a /etc/hdparm.conf
fi

for dev in /dev/sd?; do
  echo "/dev/$dev { }" |tee -a /etc/hdparm.conf
done
