#!/usr/bin/env python

# reduce password delay to a manageable level
# https://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password
# https://askubuntu.com/questions/877385/how-can-i-lower-the-delay-after-incorrectly-entered-login-and-sudo-passwords

# It seems that the order of lines in pam configuration matters, therefore
# perform replacements inline.

# The delay is not precise. Sometimes an extra 200 ms is added on the first
# failed attempt.

import os, re

pam_dir = '/etc/pam.d'
for basename in os.listdir(pam_dir):
    lines = []
    with open(os.path.join(pam_dir, basename), 'r+') as f:
        for line in f.readlines():
            if re.match(r'auth.*pam_unix\.so', line):
                line = line.replace(' nodelay', '')
                line = line.strip() + " nodelay\n"
            elif basename == 'login' and re.match(r'auth.*pam_faildelay.so.*delay=', line):
                match = re.match(r'(auth.*pam_faildelay.so.*delay=)(\d+)(.*)', line)
                line = match.group(1) + '500000' + match.group(3) + "\n"
            elif basename == 'sshd' and re.match('@include.*common-auth', line):
                lines.append("auth optional pam_faildelay.so delay=400000\n")
            elif basename == 'su' and re.match('@include.*common-auth', line):
                lines.append("auth optional pam_faildelay.so delay=200000\n")
            elif basename == 'sudo' and re.match('@include.*common-auth', line):
                lines.append("auth optional pam_faildelay.so delay=200000\n")
            lines.append(line)
        f.seek(0)
        f.write(''.join(lines))
