#!/usr/bin/env ruby

# reduce password delay to a manageable level
# https://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password
# https://askubuntu.com/questions/877385/how-can-i-lower-the-delay-after-incorrectly-entered-login-and-sudo-passwords

# It seems that the order of lines in pam configuration matters, therefore
# perform replacements inline.

autoload :FileUtils, 'fileutils'

def edit_file(path)
  contents = File.read(path)
  modified = yield contents
  File.open(path + '.part', 'w') do |f|
    f << modified
  end
  FileUtils.mv(path + '.part', path)
end

PAM_DIR = '/etc/pam.d'
Dir.children(PAM_DIR).each do |basename|
  path = File.join(PAM_DIR, basename)
  edit_file(path) do |contents|
    lines = contents.split("\n").map do |line|
      if line =~ /pam_unix.so/ && line !~ /pam_unix.so nodelay/
        line.sub!(/pam_unix.so /, 'pam_unix.so nodelay ')
      end
      if line =~ /^auth\s+optional\s+pam_faildelay.so/
        line = "##{line}"
      end
      line
    end
    lines.join("\n")
  end
end

edit_file('/etc/pam.d/common-auth') do |contents|
  "auth       optional   pam_faildelay.so  delay=300000\n#{contents}"
end

edit_file('/etc/login.defs') do |contents|
  lines = contents.split("\n").map do |line|
    if line =~ /^FAIL_DELAY=/
      line = "##{line}"
    end
    line
  end
  lines << "FAIL_DELAY=0"
  lines.join("\n")
end
