#!/bin/sh

# Check acpi events with acpi_listen.

set -e

BASE=`dirname $0`/..

. $BASE/script/common.sh

if ! is_laptop; then
  echo 'error: not a laptop' 1>&2
  exit 1
fi

check_deps() {
  if false; then
  # There isn't /etc/acpi/actions (any more?).
  # The next check for events covers actions too.
  if ! test -d /etc/acpi/actions; then
    echo "Missing /etc/acpi/actions" 1>&2
    if ! dpkg-query -s acpi-support >/dev/null 2>&1; then
      echo Possible reason: acpi-support is not installed 1>&2
    fi
    exit 1
  fi
  fi

  if ! test -d /etc/acpi/events; then
    echo "Missing /etc/acpi/events" 1>&2
    if ! dpkg-query -s acpi-support >/dev/null 2>&1; then
      echo Possible reason: acpi-support is not installed 1>&2
    fi
    exit 1
  fi
}

if dmidecode -t system |grep -q 'ThinkPad X280'; then
  echo 'Installing for ThinkPad X280'
  check_deps
  install -m 555 -o root -g root -t /etc/acpi "$BASE"/config/acpi/sleep-key.sh
  install -m 444 -o root -g root -t /etc/acpi/events "$BASE"/config/acpi/events/sleep-key
  update-rc.d acpid defaults
  /etc/init.d/acpid start
else
  echo 'Not installing - system not recognized'
fi
