#!/usr/bin/env ruby

# TODO: connecting to network without PSK after boot
# doesn't bring up the wireless interface? run ifconfig up manually?

# Inspiration: https://github.com/dmelo/vswm

autoload :YAML, 'yaml'
autoload :FileUtils, 'fileutils'
autoload :Tempfile, 'tempfile'
autoload :JSON, 'json'
autoload :OptionParser, 'optparse'
#gem 'childprocess'
autoload :ChildProcess, 'childprocess'
require_relative '../lib/ruby/global_helpers'

class Error < StandardError
end

class WpaSupplicantFailed < Error
end

class InterfaceNotFound < Error
end

class NoIpAddress < Error
end

class NoDefaultGateway < Error
end

class CalledProcessError < Error
end

module Sub

  module_function def uncheck_call(cmd, env: nil)
    start_process(cmd, env: env).tap do |process|
      process.wait
    end
  end

  module_function def start_and_forward(cmd, env: nil)
    puts "[CWR] Starting: #{cmd.join(' ')}"
    process = ChildProcess.new(*cmd)
    process.io.inherit!
    rd, wr = IO.pipe
    apply_env(process, env)
    process.start
    p process.wait
  end

  module_function def check_call(cmd, env: nil)
    process = uncheck_call(cmd, env: env)
    check_exit_code(process, cmd)
  end

  module_function def check_output(cmd, env: nil)
    puts "[CWR] Get output: #{cmd.join(' ')}"
    process = ChildProcess.new(*cmd)
    process.io.inherit!
    process.io.stdout = Tempfile.new("child-output")
    process.io.stderr = Tempfile.new("child-error")
    begin
      apply_env(process, env)
      process.start
      process.wait
      check_exit_code(process, cmd)
      process.io.stdout.rewind
      process.io.stdout.read
    ensure
      process.io.stdout.close
      process.io.stderr.close
    end
  end

  module_function def start_process(cmd, env: nil)
    puts "[CWR] Starting: #{cmd.join(' ')}"
    process = ChildProcess.new(*cmd)
    process.io.inherit!
    apply_env(process, env)
    process.start
    process
  end

  module_function def start_process_pipe(cmd, env: nil)
    puts "[CWR] Starting pipe: #{cmd.join(' ')}"
    rd, wr = IO.pipe
    pid = fork do
      rd.close
      STDOUT.reopen(wr)
      STDERR.reopen(wr)
      wr.close

      if env
        env.each do |k, v|
          ENV[k] = v
        end
      end

      exec(*cmd)
    end

    wr.close
    cmd_name = File.basename(cmd.first)
    thread = Thread.new do
      loop do
        chunk = rd.readline
        if chunk.nil?
          break
        end
        STDOUT << "[#{cmd_name}] #{chunk}"
      rescue EOFError
        # swallow
      end
    end

    {pid: pid, thread: thread}
  end

  private

  module_function def apply_env(process, env)
    if env
      env.each do |k, v|
        process.environment[k.to_s] = v
      end
    end
  end

  module_function def format_cmd(cmd)
    cmd.join(' ')
  end

  module_function def check_exit_code(process, cmd)
    unless process.exit_code == 0
      raise CalledProcessError, "Failed to execute: #{format_cmd(cmd)} (exit code #{process.exit_code})"
    end
  end
end

module Utils
  module_function def monotime
    Process.clock_gettime(Process::CLOCK_MONOTONIC)
  end

  module_function def have(basename)
    !!path_dirs.detect do |dir|
      File.exist?(File.join(dir, basename))
    end
  end

  private

  module_function def path_dirs
    @path_dirs ||= ENV.fetch('PATH').split(':')
  end
end

module Helpers

  private

  def clear_interface_ips(ifname)
    # https://superuser.com/questions/153559/how-can-i-clear-the-ip-address-of-ethernet-interface-without-cycling-the-interfa
    Sub.check_call(['ip', 'addr', 'flush', 'dev', ifname])
  end

  def get_interface_ip(ifname)
    output = Sub.check_output(['ip', '-j', 'address', 'show', ifname])
    result = JSON.parse(output)
    if ais = result.first['addr_info']
      if ais.empty?
        #raise NoIpAddress, "Empty addr_info for #{ifname}"
        return nil
      end
      ais.each do |ai|
        if (family = ai.fetch('family')) == 'inet'
          return ai.fetch('local')
        end
      end
    end
  end

  def get_interface_ip!(ifname)
    get_interface_ip(ifname) or raise NoIpAddress, "No IP address for #{ifname}"
  end

  def get_default_gateway
    lines = Sub.check_output(%w(netstat -rn)).split("\n")
    lines.each do |line|
      if line.start_with?('0.0.0.0')
        return line.split(/\s+/, 2).first
      end
    end
    raise NoDefaultGateway
  end

  def unblock_rfkill
    if Utils.have('rfkill')
      output = Sub.check_output(%w(rfkill))
      output.split("\n").each do |line|
        id, type, device, soft, hard = line.strip.split(/\s+/)
        if type == 'wlan' && soft == 'blocked'
          puts("Unblocking rfkill")
          Sub.check_call(['rfkill', 'unblock', id])
        end
      end
    end
  end

  def get_iwconfig(ifname)
    output = Sub.check_output(['iwconfig', ifname])
    state = {associated: false}
    if output =~ /\bESSID:"([^"]*)"/
      # SSID is escaped here, try to interpret it as UTF-8
      # (happened in a Paris hotel at least) and un-escape
      ssid = $1
      if ssid.include?(?\\)
        warn "Unescaping SSID: #{ssid}"
        ssid.gsub!(%r,\\x(\w\w),) { Integer($1, 16).chr }.force_encoding('utf-8')
      end
      state[:ssid] = ssid
    elsif output =~ /\bESSID:([^\s]+)/
      state[:ssid] = $1
    end
    if state[:ssid] == 'off/any'
      state[:no_ssid] = true
    end

    if output =~ /Access Point: (?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}/
      state[:associated] = true
    end

    state
  end

  def get_wpa_state(ifname)
    state = {}
    begin
      output = Sub.check_output(['wpa_cli', '-i', ifname, 'status'])
    rescue CalledProcessError
    else
      if output =~ /\bwpa_state=(\w+)/
        state[:wpa_state] = $1
      end
      state[:wpa_completed] = state[:wpa_state] == 'COMPLETED'
    end
    state
  end
end

class Runner
  include Helpers
  include GlobalHelpers

  def initialize(**opts)
    @options = opts.dup.freeze

    if auto?
      @keep_wired_up = !!begin
        Sub.check_output(%w(dmidecode -s system-family)).strip =~ /^ThinkPad X280/
      rescue CalledProcessError
        false
      end
    end
  end

  attr_reader :options

  def keep_wired_up?
    @keep_wired_up
  end

  def ssid
    options.fetch(:ssid)
  end

  def psk
    options[:psk]
  end

  def auth_options
    options.slice(*%i(auth identity ca_cert_path user_cert_path user_key_path user_key_password))
  end

  def state_dir
    options.fetch(:state_dir)
  end

  def auto?
    !!options[:auto]
  end

  def connected_wired?
    @connected == :wired
  end

  def connected_wireless?
    @connected == :wireless
  end

  def delete_processes(*names)
    names.each do |proc_name|
      Sub.uncheck_call(['pkill', proc_name])
    end
    names.each do |proc_name|
      Sub.uncheck_call(['pkill', '-9', proc_name])
    end
  end

  def run
    identify_interfaces

    if auto? && keep_wired_up?
      wired_ifnames.each do |ifname|
        Sub.uncheck_call(['ifconfig', ifname, 'up'])
      end
    end

    Sub.uncheck_call(%w,service NetworkManager stop,)

    delete_processes(*%w(ifdown ifup dhclient wpa_supplicant NetworkManager))

    done = false
    if auto? && wired_ifnames.any?
      if @wired_ifname = find_active_wired_ifname
        puts "Wired interface up: #{wired_ifname}"
        connect_wired
        done = true
      end
    end

    unless done
      connect_wireless
    end
  end

  def connect_wireless
    @connected = nil

    if auto? && keep_wired_up?
      wired_ifnames.each do |ifname|
        clear_interface_ips(ifname)
      end
    else
      wired_ifnames.each do |ifname|
        Sub.uncheck_call(['ifconfig', ifname, 'down'])
      end
    end

    @wireless_ifname = wireless_ifnames.first
    unless wireless_ifname
      raise "No wireless interfaces?"
    end

    %w(ifdown ifup dhclient wpa_supplicant).each do |proc_name|
      Sub.uncheck_call(['pkill', '-9', proc_name])
    end

    if have_ifdown = Utils.have('ifdown')
      Sub.uncheck_call(['ifdown', wireless_ifname])
      wired_ifnames.each do |ifname|
        Sub.uncheck_call(['ifdown', ifname])
      end
    end
    Sub.uncheck_call(%w,service NetworkManager stop,)
    delete_processes(*%w(NetworkManager))

    unblock_rfkill

    Sub.check_call(['ifconfig', wireless_ifname, 'up'])

    start_wpa_supplicant

    puts('Running dhclient')
    Sub.check_call(['dhclient', '-v', wireless_ifname])

    FileUtils.mkdir_p(state_dir)
    path = File.join(state_dir, 'config.json')
    @config = {
      ssid: ssid,
      psk: psk,
      auth_options: auth_options,
      interface: wireless_ifname,
      ip: get_interface_ip!(wireless_ifname),
      gateway: get_default_gateway,
    }
    File.open(path, 'w') do |f|
      f << JSON.dump(@config)
    end

    @connected = :wireless

    # On a desktop once a connection is established it will stay up,
    # unless it requires auth in which case we need to babysit
    # wpa_supplicant.
    # On a laptop connection will be broken after suspend & resume,
    # therefore we need to keep it.
    if laptop?
      keep
    end
  end

  def find_active_wired_ifname
    wired_ifnames.detect do |ifname|
      path = "/sys/class/net/#{ifname}/operstate"
      begin
        File.read(path).strip == 'up'
      rescue IOError, SystemCallError
        false
      end
    end
  end

  def connect_wired
    @connected = nil

    wireless_ifnames.each do |ifname|
      clear_interface_ips(ifname)
    end

    Sub.check_call(['ifconfig', wired_ifname, 'up'])

    Sub.check_call(['dhclient', '-v', wired_ifname])

    # Assuming, should check that the connection actually worked.
    @connected = :wired
  end

  def keep
    need_start = false
    loop do
      begin
        if need_start
          start_wpa_supplicant
          # TODO check if we already have an IP address
          puts('Running dhclient')
          Sub.check_call(['dhclient', '-v', wireless_ifname])
          need_start = false
        end

        get_current_state

        if auto? && ifname = state[:active_wired_ifname]
          unless connected_wired?
            @wired_ifname = ifname
            connect_wired
            sleep 3
          end
          sleep 3
          next
        end

        if !state[:ip]
          puts "No IP address"
          raise NoIpAddress
        end

        if @state == :started && auth? && !state[:ip] && state[:wpa_completed]
          puts "Lost IP address after WPA completed, reconnecting"
          raise NoIpAddress
        end

        # Checking WPA state here even if PSK isn't set - the block
        # should never activate since without PSK there won't be any
        # WPA state to begin with.
        if state[:wpa_completed]
          sleep 3
          next
        end

        if state[:no_ssid]
          raise WpaSupplicantFailed, 'ssid is off/any, bad auth to wpa supplicant?'
        end

        # TODO check that the current SSID is the one that was requested
        # by the user.

        elapsed = Utils.monotime - started_at

        if auth?
          if elapsed > options.fetch(:wpa_supplicant_timeout)
            raise WpaSupplicantFailed, "Giving up on wpa association after #{options.fetch(:wpa_supplicant_timeout)} seconds"
          end

          if @wpa_exited
            raise WpaSupplicantFailed, "wpa_supplicant unexpectedly terminated with exit code #{wpa_process.exit_code}"
          end

          puts 'ssid: %s, wpa: %s, elapsed: %d' % [state[:ssid], state[:wpa_state], elapsed]
        else
          puts 'ssid: %s, elapsed: %d' % [state[:ssid], elapsed]
        end

        sleep 3
      rescue WpaSupplicantFailed, NoIpAddress
        need_start = true
        Sub.uncheck_call(%w(pkill -9 wpa_supplicant))
        sleep 1
      end
    end
  end

  def list_wireless_ssids
    identify_interfaces
    wireless_ifname = wireless_ifnames.first
    output = Sub.check_output(['iwlist', wireless_ifname, 'scanning'])
    ssids = []
    output.split("\n").each do |line|
      if line =~ /\bESSID:"(.+)"\z/
        ssids << $1
      end
    end
    ssids.uniq!.sort!
    if ssids.any?
      ssids.each do |ssid|
        p ssid
      end
    else
      puts "No wireless networks observed"
    end
  end

  private

  attr_reader :wired_ifnames
  attr_reader :wired_ifname
  attr_reader :wireless_ifnames
  attr_reader :wireless_ifname

  def auth?
    psk || auth_options[:auth]
  end

  def identify_interfaces
    wireless = []
    wired = []

    output = Sub.check_output(%w(iwconfig))
    # "no wireless extensions" lines are printed to standard error
    output.split(/[\r\n]+/).each do |line|
      if line =~ %r,\A(\w+),
        ifname = $1
        wireless << ifname
      end
    end

    output = Sub.check_output(%w(ip -j a))
    infos = {}
    JSON.parse(output).each do |info|
      if info.fetch('link_type') == 'ether'
        ifname = info.fetch('ifname')
        unless wireless.include?(ifname)
          wired << ifname
        end
      end
    end

    @wired_ifnames = wired
    @wireless_ifnames = wireless
  end

  attr_reader :wpa_process_info
  attr_reader :started_at

  def start_wpa_supplicant
    puts "[CWR] Preparing to start wpa_supplicant for #{wireless_ifname}"
    @state = :starting
    if wpa_process_info
      begin
        Process.kill('TERM', wpa_process_info.fetch(:pid))
      rescue SystemCallError
      end
      begin
        wpa_process_info.fetch(:thread).kill
      rescue ThreadError
      end
      @wpa_process_info = nil
    end
    @wpa_exited = false

    Sub.uncheck_call(%w,service NetworkManager stop,)
    delete_processes(*%w(NetworkManager))

    dir = '/etc/network/interfaces.d'
    if File.exist?(dir)
      contents = "iface #{wireless_ifname} inet dhcp\n"
      if auth?
        contents << "  wpa-ssid \"#{ssid}\"\n"
      else
        contents << "  wireless-essid \"#{ssid}\""
      end
      File.open(File.join(dir, wireless_ifname), 'w') do |f|
        f << contents
      end
    end

    Sub.check_call(['iwconfig', wireless_ifname, 'essid', ssid])

    if auth?
      continue_starting_wpa_supplicant
    else
      really_set_ssid(ssid)
      @started_at = Utils.monotime
      @state = :started
    end
  end

  def really_set_ssid(ssid)
    loop do
      state = get_iwconfig(wireless_ifname)
      if state[:ssid] == ssid && state[:associated]
        break
      end

      puts "Resetting ssid for #{wireless_ifname}"

      Sub.check_call(['iwconfig', wireless_ifname, 'essid', ssid])
      sleep 1
    end
  end

  def continue_starting_wpa_supplicant
    contents = ''
    if psk
      contents << "  key_mgmt=WPA-PSK\n"
      contents << "  psk=\"#{psk}\"\n"
    elsif auth = auth_options[:auth]
      auth_map = {
        'tls' => 'TLS',
      }
      contents << "  key_mgmt=WPA-EAP\n"
      contents << "  eap=#{auth_map.fetch(auth)}\n"
      {
        identity: :identity,
        ca_cert_path: :ca_cert,
        user_cert_path: :client_cert,
        user_key_path: :private_key,
        user_key_password: :private_key_passwd,
      }.each do |k, mapped_k|
      p auth_options
        if value = auth_options[k]
        p [k,mapped_k,value]
          contents << "  #{mapped_k}=\"#{value}\"\n"
        end
      end
      puts contents
    end
    contents = <<-EOT
      ctrl_interface=/run/wpa_supplicant
      #ap_scan=0
      network={
        scan_ssid=1
        ssid="#{ssid}"
        #{contents}
        #pairwise=CCMP TKIP
        #group=CCMP TKIP
      }
EOT
    # Debian systems
    wpa_conf_dir = '/etc/network/wpa_supplicant.conf.d'
    unless File.exist?(wpa_conf_dir)
      # Ubuntu systems
      warn "#{wpa_conf_dir} does not exist, using /tmp"
      wpa_conf_dir = '/tmp'
    end
    wpa_conf_path = File.join(wpa_conf_dir, wireless_ifname)
    File.open(wpa_conf_path, 'w') do |f|
      f << contents
    end

    begin
      Sub.check_call(%W(wpa_cli -i #{wireless_ifname} status))
    rescue CalledProcessError
    else
      Sub.check_call(%W(wpa_cli -i #{wireless_ifname} terminate))
      sleep 1
    end

    puts("Starting wpa_supplicant for #{wireless_ifname}")
    wpa_supplicant_log_path = '/tmp/wpa_supplicant.log'
    # TODO detach from controlling terminal here
    binary = 'wpa_supplicant'
    #binary = '/home/me/apps/exp/hostap/wpa_supplicant/wpa_supplicant'
    @wpa_process_info = Sub.start_process_pipe([binary,
      '-D', 'nl80211,wext', '-i', wireless_ifname,
      '-f', wpa_supplicant_log_path,
      '-c', wpa_conf_path, '-d',
    ])
    if File.exist?(wpa_supplicant_log_path)
      FileUtils.chmod(0o644, wpa_supplicant_log_path)
    end

    Thread.new do
      pid = wpa_process_info.fetch(:pid)
      exitstatus = Process.waitpid(pid)
      puts "wpa supplicant exited with #{$?.exitstatus}"
      wpa_process_info[:exit_status] = $?.exitstatus
    ensure
      @wpa_exited = true
    end

    @started_at = Utils.monotime
    @state = :started
    loop do
      get_current_state

      if state[:no_ssid]
        raise WpaSupplicantFailed, 'ssid is off/any, bad auth to wpa supplicant?'
      end

      if state[:wpa_completed]
        break
      end

      if (elapsed = Utils.monotime - started_at) > options.fetch(:wpa_supplicant_timeout)
        raise WpaSupplicantFailed, "Giving up on wpa association after #{options.fetch(:wpa_supplicant_timeout)} seconds"
      end

      if @wpa_exited
        status = wpa_process_info[:exit_status]
        pp status
        if status
          raise WpaSupplicantFailed, "wpa_supplicant unexpectedly terminated with exit code #{status}"
        else
          raise WpaSupplicantFailed, "wpa_supplicant unexpectedly terminated and exit code is not available"
        end
      end

      puts 'ssid: %s, wpa: %s, elapsed: %d' % [state[:ssid], state[:wpa_state], elapsed]
      sleep 1
    end
  rescue CalledProcessError => exc
    new_exc = WpaSupplicantFailed.new("#{exc.class}: #{exc}")
    new_exc.backtrace = exc.backtrace
    raise new_exc
  end

  attr_reader :state

  def get_wireless_state
    state = get_iwconfig(wireless_ifname)
    state.update(ip: get_interface_ip(wireless_ifname))

    if auth?
      state.update(get_wpa_state(wireless_ifname))
    end

    if state[:wpa_completed] && !state[:associated]
      # Funny state that wpa_supplicant ends up in, where it thinks everything
      # is fine but the interface is not associated
      # (and because wpa_supplicant thinks everything is fine, it does not
      # do anything to fix the situation).
      state.delete(:wpa_completed)
    end

    state
  end

  def get_current_state
    state = get_wireless_state

    if auto?
      state[:active_wired_ifname] = find_active_wired_ifname
    end

    @state = state.compact
  end

  def default_gw_ok?
    output = Sub.check_output(%w(netstat -rn))
    lines = output.split("\n").select do |line|
      line.start_with?('0.0.0.0')
    end
    if lines.length > 1
      puts "Multiple default gateways??"
      return false
    end
    if lines.length == 0
      puts "No default gateway"
      return false
    end
    gw = lines.first.split(/\s+/)[1]
    puts "Default gateway: #{gw}"
    true
  end

  def start_dhclient
    Sub.uncheck_call(%w(pkill dhclient))
    Sub.check_call(['dhclient', '-v', wireless_ifname])
  end
end

options = {
  wpa_supplicant_timeout: 10,
  state_dir: '/run/wireless',
}
OptionParser.new do |opts|
  opts.banner = "Usage: connect-wireless [options] ssid [psk]"

  opts.on("-a", "--auto", "Auto switch between wired & wireless") do
    options[:auto] = true
  end

  opts.on("-r", "--resume", "Restore configuration after wake-up") do
    options[:resume] = true
  end

  opts.on("-k", "--keep", "Stay running to maintain specified configuration") do
    options[:keep] = true
  end

  opts.on("-d", "--daemon", "Daemonize") do
    options[:daemonize] = true
  end

  opts.on("-P", "--pidfile PATH", "Path to pidfile when daemonizing") do |v|
    options[:pidfile_path] = v
  end

  opts.on("-l", "--log PATH", "Log to specified path instead of standard output") do |v|
    options[:log_path] = v
  end

  opts.on('-L', '--list', 'List SSIDs') do
    options[:list_ssids] = true
  end

  opts.on("-t", "--wpa-supplicant-timeout TIMEOUT", "Timeout to wait for wpasupplicant") do |v|
    options[:wpa_supplicant_timeout] = Float(v)
  end

  opts.on('-w', '--known', 'Resolve argument as a known network') do
    options[:known] = true
  end

  opts.on('--state-dir PATH', 'Path to state directory to use') do |v|
    options[:state_dir] = v
  end
end.parse!

if options[:list_ssids]
  Runner.new.list_wireless_ssids
  exit
end

ssid, psk = ARGV
if ssid.nil?
  raise 'Usage'
end

if options[:known]
  if psk
    raise "PSK cannot be given when using a known network"
  end

  dir = File.join(File.dirname(__FILE__), '../config/wireless-networks.d')
  unless File.exist?(dir)
    raise "Missing known networks directory: #{dir}"
  end
  networks = {}
  Dir.entries(dir).each do |bn|
    next if bn == '.' || bn == '..'
    begin
      this_contents = File.open(File.join(dir, bn)) do |f|
        YAML.load(f)
      end
      networks.update(this_contents)
    rescue Psych::Exception => exc
      puts "Error loading #{bn}: #{exc.class}: #{exc}"
    end
  end

  info = networks[ssid]&.transform_keys(&:to_sym)
  unless info
    raise "Network alias #{ssid} not known"
  end
  ssid = info.fetch(:ssid)
  psk = info[:psk]

  puts "Connecting to #{ssid}"
else
  info = {ssid: ssid, psk: psk}
end

if options[:daemonize]
  unless options[:log_path]
    raise "Log destination must be specified when daemonizing"
  end

  unless options[:pidfile_path]
    raise "Pidfile path must be specified when daemonizing"
  end
end

Runner.new(**options.merge(info)).run
