#!/bin/sh

# Disable recent files.
# https://alexcabal.com/disabling-gnomes-recently-used-file-list-the-better-way
# See also: https://unix.stackexchange.com/questions/74031/disable-recently-used-in-gtk-file-directory-selector

set -e

gsettings set org.gnome.desktop.privacy remember-recent-files false
