#!/bin/sh

# devuan
if false; then
sudo which sysv-rc-conf || (sudo apt-get update && sudo apt-get install sysv-rc-conf)

sudo update-rc.d avahi-daemon disable
else
:

fi

sudo apt-get remove avahi-daemon
