#!/bin/sh

# Disable recent files.
# https://alexcabal.com/disabling-gnomes-recently-used-file-list-the-better-way
# See also: https://unix.stackexchange.com/questions/74031/disable-recently-used-in-gtk-file-directory-selector

set -e

# Method 1

gsettings set org.gnome.desktop.privacy remember-recent-files false

# Method 2

: > ~/.local/share/recently-used.xbel
# Requires root
#chattr +i ~/.local/share/recently-used.xbel
# Doesn't work because the file is rewritten
#chmod 000 ~/.local/share/recently-used.xbel
