#!/usr/bin/env ruby

require 'yaml'

def blkid(device)
  status = `blkid #{device}`
  if status =~ /LABEL="([^"]+)/
    label = $1
  end
  {label: label}
end

disks = (Dir['/dev/sd?'] + Dir['/dev/nvme?n?']).sort
disk_infos = {}
disks.each do |disk|
  pattern = if disk =~ /nvme/
    "#{disk}p?"
  else
    "#{disk}?"
  end
  parts = Dir[pattern].sort
  status = `fdisk -l #{disk}`
  size = "#{status.split(/\s+/)[2]} #{status.split(/\s+/)[3].sub(',', '')}"
  if status =~ /Disk model: ([^\n]+)/
    model = $1
  end
  part_infos = {}
  parts.each do |part|
    status = `fdisk -l #{part}`
    part_size = "#{status.split(/\s+/)[2]} #{status.split(/\s+/)[3].sub(',', '')}"
    part_infos[part] = {size: part_size}
  end
  status = `smartctl -a #{disk}`
  if status =~ /Serial [nN]umber:\s+(\S+)/
    serial = $1
  end
  if status =~ /Device Model:\s+(.+?)\n/
    model = $1
  end
  disk_infos[disk] = {
    parts: parts,
    size: size,
    part_infos: part_infos,
    model: model,
    serial: serial,
  }
end

dms = Dir['/dev/mapper/*'].sort
dm_infos = {}
dms.each do |dm|
  next if File.basename(dm) == 'control'
  dev_num = File.basename(File.readlink(dm))
  status = `cryptsetup status #{dm}`
  if status =~ /device:\s+(\S+)/
    device = $1
  else
    raise "cryptsetup failed for #{dm}"
  end
  blkid_status = blkid(dm)

  if device == '(null)'
    warn "warning: dm #{dm} has null device"
    next
  end

  dm_infos[dm] = {
    device: device,
    label: blkid_status[:label],
    device_num: dev_num,
  }
  parent = if device =~ /nvme/
    device[...-2]
  elsif device =~ /\bsd/
    device[...-1]
  else
    raise NotImplementedError
  end
  m = disk_infos[parent][:part_infos][device]
  m.update(mapper: dm, mapper_label: blkid_status[:label], mapper_device_num: dev_num)
end

disk_infos.each do |disk, di|
  puts
  puts "#{'%-10s' % File.basename(disk)}   #{'%10s' % di[:size]}  #{'%-20s' % di[:model]}      Serial: #{di[:serial]}"
  di[:part_infos].each do |part, pi|
    blkid_status = blkid(part)

    final_part = pi[:mapper] || part
    status = `df -h #{final_part}`.split("\n")[1]
    fs, size, used, avail, perc, mounted = status.split(/\s+/)
    if fs == 'udev'
      fs, size, used, avail, perc, mounted = nil
    end
    mapper_info = if pi[:mapper]
      label = if blkid_status[:mapper_label]
        " label=#{pi[:mapper_label]}"
      else
        ''
      end
      " via #{'%-21s' % File.basename(pi[:mapper])} #{label}(#{pi[:mapper_device_num]})"
    else
      ' ' * 33
    end
    mount_info = if fs
      " -> #{'%-20s' % mounted} #{'%4s' % perc} used"
    else
      ''
    end
    label = if blkid_status[:label]
      " [#{blkid_status[:label]}]"
    else
      ''
    end
    puts "  #{'%-10s' % File.basename(part)} #{'%10s' % pi[:size]} #{label}#{mapper_info}#{mount_info}"
  end
end
puts

#puts disk_infos.to_yaml
