#!/usr/bin/env ruby

require 'json'
require 'yaml'

def blkid(device)
  status = `blkid #{device}`
  if status =~ /LABEL="([^"]+)/
    label = $1
  end
  {label: label}
end

disks = (Dir['/dev/sd?'] + Dir['/dev/nvme?n?']).sort
disk_infos = {}
disks.each do |disk|
  pattern = if disk =~ /nvme/
    "#{disk}p?"
  else
    "#{disk}?"
  end
  parts = Dir[pattern].sort
  status = `fdisk -l #{disk}`
  if status.strip.empty?
    disk_infos[disk] = {
      model: '???',
      serial: '???',
      part_infos: {},
    }
  else
    size = "#{status.split(/\s+/)[2]} #{status.split(/\s+/)[3].sub(',', '')}"
    if status =~ /Disk model: ([^\n]+)/
      model = $1
    end
    part_infos = {}
    parts.each do |part|
      status = `fdisk -l #{part}`
      part_size = "#{status.split(/\s+/)[2]} #{status.split(/\s+/)[3].sub(',', '')}"
      part_infos[part] = {size: part_size}
    end
    status = `smartctl -a #{disk}`
    if status =~ /Serial [nN]umber:\s+(\S+)/
      serial = $1
    end
    if status =~ /Device Model:\s+(.+?)\n/
      model = $1
    end
    disk_infos[disk] = {
      parts: parts,
      size: size,
      part_infos: part_infos,
      model: model,
      serial: serial,
    }
  end
  if disk =~ /sd/
    disk_name = File.basename(disk)
    scsi_id = File.basename(File.readlink("/sys/block/#{disk_name}/device"))
    disk_infos[disk].update(
      scsi_id: scsi_id,
    )
  end
end

dms = Dir['/dev/mapper/*'].sort
dm_infos = {}
dms.each do |dm|
  next if File.basename(dm) == 'control'
  dev_num = File.basename(File.readlink(dm))

  info = `lsblk -Jdo TYPE #{dm}`
  info = JSON.parse(info).fetch('blockdevices')[0]
  type = info.fetch('type')
  if type == 'crypt'
    status = `cryptsetup status #{dm}`
    if status =~ /device:\s+(\S+)/
      device = $1
    else
      raise "'cryptsetup status' failed or produced unexpected output for '#{dm}'"
    end
    blkid_status = blkid(dm)
  else
    # TODO
    device = nil
  end

  if device.nil? || device == '(null)'
    warn "warning: dm #{dm} has null device"
    next
  end

  dm_infos[dm] = {
    device: device,
    label: blkid_status[:label],
    device_num: dev_num,
  }
  parent = if device =~ /nvme/
    device[...-2]
  elsif device =~ /\bsd\w\d\z/
    device[...-1]
  elsif device =~ /\bsd\w\z/
    device
  else
    raise NotImplementedError
  end
  m = disk_infos[parent][:part_infos][device] || {}
  m.update(mapper: dm, mapper_label: blkid_status[:label], mapper_device_num: dev_num)
end

class IOStats
  def initialize(device_name)
    @device_name = File.basename(device_name)
  end

  attr_reader :device_name

  def stats
    @stats ||= begin
      contents = File.read(File.join('/sys/block', device_name, 'stat'))
      contents.strip.split(%r,\s+,).map { |v| Integer(v) }
    end
  end

  def sector_size
    # I think it's always 512 regardless of file system block size
    512
  end

  def reads_completed
    stats[0]
  end

  def reads_merged
    stats[1]
  end

  def sectors_read
    stats[2]
  end

  def bytes_read
    sectors_read * sector_size
  end

  def milliseconds_spent_reading
    stats[3]
  end

  def time_spent_reading
    milliseconds_spent_reading / 1000.0
  end

  def writes_completed
    stats[4]
  end

  def writes_merged
    stats[5]
  end

  def sectors_written
    stats[6]
  end

  def bytes_written
    sectors_written * sector_size
  end

  def milliseconds_spent_writing
    stats[7]
  end

  def time_spent_writing
    milliseconds_spent_writing / 1000.0
  end

  def ios_in_progress
    stats[8]
  end

  def milliseconds_spent_current_io
    stats[9]
  end

  def weighted_milliseconds_spent_current_io
    stats[10]
  end

  def discards_completed
    stats[11]
  end

  def discards_merged
    stats[12]
  end

  def sectors_discarded
    stats[13]
  end

  def bytes_discarded
    sectors_discarded * sector_size
  end

  def milliseconds_spent_discarding
    stats[14]
  end

  def time_spent_discarding
    milliseconds_spent_discarding / 1000.0
  end

  def flushes_completed
    stats[15]
  end

  def milliseconds_spent_flushing
    stats[16]
  end

  def time_spent_flushing
    milliseconds_spent_flushing / 1000.0
  end
end

SIZE_UNITS = %w(bytes KB MB GB TB)

def friendly_size(size, suffix: nil)
  if size.respond_to?(:nan?) && size.nan?
    return "-- bytes#{suffix}"
  end

  SIZE_UNITS.each do |unit|
    if size < 5*1024
      precision = [2-size.round.to_s.length, 0].max
      return "#{"%.#{precision}f" % size} #{unit}#{suffix}"
    end

    size /= 1024.0
  end

  precision = [2-size.round.to_s.length, 0].max
  "#{"%.#{precision}f" % size} PB#{suffix}"
end

TIME_UNITS = [
  ['seconds', 60],
  ['minutes', 60],
  ['hours', 24],
  ['days', 1_000_000],
]

def friendly_time(time)
  TIME_UNITS.each do |(unit, max)|
    if time < max/2
      precision = [2-time.round.to_s.length, 0].max
      return "#{"%.#{precision}f" % time} #{unit}"
    end

    time /= max.to_f
  end

  raise "Should never get here"
end

disk_infos.each do |disk, di|
  puts
  name = if di[:scsi_id]
    "#{File.basename(disk)} (#{di[:scsi_id]})"
  else
    File.basename(disk)
  end
  puts "#{'%-10s' % name}   #{'%10s' % di[:size]}  #{'%-20s' % di[:model]}      Serial: #{di[:serial]}"

  stats = IOStats.new(disk)
  puts "stats: \
#{friendly_size(stats.bytes_read)} read \
in #{friendly_time(stats.time_spent_reading)} \
(#{friendly_size(stats.bytes_read / stats.time_spent_reading, suffix: '/s')}), \
#{friendly_size(stats.bytes_written)} written \
in #{friendly_time(stats.time_spent_writing)} \
(#{friendly_size(stats.bytes_written / stats.time_spent_writing, suffix: '/s')})\
"

  di[:part_infos].each do |part, pi|
    blkid_status = blkid(part)

    final_part = pi[:mapper] || part
    status = `df -h #{final_part}`.split("\n")[1]
    fs, size, used, avail, perc, mounted = status.split(/\s+/)
    if fs == 'udev'
      fs, size, used, avail, perc, mounted = nil
    end
    mapper_info = if pi[:mapper]
      label = if blkid_status[:mapper_label]
        " label=#{pi[:mapper_label]}"
      else
        ''
      end
      " via #{'%-21s' % File.basename(pi[:mapper])} #{label}(#{pi[:mapper_device_num]})"
    else
      ' ' * 33
    end
    mount_info = if fs
      " -> #{'%-20s' % mounted} #{'%4s' % perc} used"
    else
      ''
    end
    label = if blkid_status[:label]
      " [#{blkid_status[:label]}]"
    else
      ''
    end
    puts "  #{'%-10s' % File.basename(part)} #{'%10s' % pi[:size]} #{label}#{mapper_info}#{mount_info}"
  end
end
puts

#puts disk_infos.to_yaml
