#!/usr/bin/env ruby

# Port forwarding docs: https://github.com/moby/moby/issues/2785

image_name, container_port, host_port = ARGV

unless host_port
  raise "Usage: docker-run-image image-name container-port host-port"
end

# gem install docker-api
require 'docker'
require 'yaml'
require 'base64'

Docker.validate_version!

config = YAML.load(File.read(File.expand_path('~/.docker/config.json')))
auth = config['auths']['https://index.docker.io/v1/']['auth']
username, password = Base64.decode64(auth).split(':')

Docker.authenticate!(username: username, password: password)

image = Docker::Image.create(fromImage: image_name)
puts "#{image_name} => #{image.id}"

containers = Docker::Container.all(all: true)
container = containers.detect do |c|
  c.info['ImageID'] == image.id
end

if container.nil?
  container = Docker::Container.create(
    Image: image_name,
  )
end

container = Docker::Container.get(container.id)

#container.delete(force: true)

status = container.info['State']['Status']
if status == 'running'
  puts "Container #{container.id} for #{image_name} is already running"
else
  puts "Starting container for #{image_name}"
  container.start!(PortBindings: {
    "#{container_port}/tcp" => [{HostPort: host_port.to_s}],
  })
end

if false
require 'byebug'
byebug
1
end

container = Docker::Container.get(container.id)
status = container.info['State']['Status']
if status != 'running'
  raise "Bad status #{status} for container #{container.id}"
end

#p image
