#!/bin/sh

set -e

start=
stop=

while getopts s:S: opt; do
  case $opt in
  s)
    start="$OPTARG"
    ;;
  S)
    stop="$OPTARG"
    ;;
  *)
    echo "Bogus option $opt" 1>&2
    exit 10
    ;;
  esac
done
shift $((OPTIND-1))

src="$1"

if test -z "$src"; then
  echo `basename $0` src 1>&2
  exit 1
fi

# https://stackoverflow.com/questions/5618363/is-there-a-way-to-use-ffmpeg-to-determine-the-encoding-of-a-file-before-transcod

info=`ffprobe -hide_banner -show_streams "$src"`
if test $? != 0; then
  echo ffprobe failed, bad file? 1>&2
  exit 2
fi

if echo "$info" |grep -q channels=2; then
  echo
  echo "2 channels, assuming Alesis output"
  
  name="`basename "$src" |sed -e 's/\.wav$//'`"
  echo "Will encode to 225 & 175 kbps mp3 to $name-225.mp3 and $name-175.mp3"
  echo "Press Enter to continue"
  read x
  echo continuing
  
  input_opts=
  if test -n "$start"; then
    input_opts="$input_opts -ss $start"
  fi
  if test -n "$stop"; then
    input_opts="$input_opts -to $stop"
  fi
  
  ffmpeg -hide_banner $input_opts -i "$src" -codec:a libmp3lame  -qscale:a 1 -threads 4 "$name"-225.mp3
  ffmpeg -hide_banner $input_opts -i "$src" -codec:a libmp3lame  -qscale:a 3 -threads 4 "$name"-175.mp3
else
  echo "Unhandled path" 1>&2
  exit 3
fi
