#!/usr/bin/env ruby

require 'find'
require 'fileutils'

start = ARGV.shift || '.'

Find.find(start) do |path|
  bn = File.basename(path)
  dn = File.dirname(path)
  begin
    bn.encode('utf-16')
  rescue Encoding::InvalidByteSequenceError
    bn.force_encoding('iso8859-1')
    p bn.encoding
    fixed_bn = bn.encode('utf-8')
    #puts "In #{dn}: #{bn} -> #{fixed_bn}"
    STDOUT << "In #{dn}: #{bn} ->"
    puts fixed_bn
    FileUtils.mv(path, File.join(dn, fixed_bn))
  end
end
