#!/bin/sh

# Self-encrypting drives may be locked. To unlock them, use sedutil-cli
# as follows:
#
# sedutil-cli --yesIreallywanttoERASEALLmydatausingthePSID PSID /dev/sdX
#
# PSID is, for HGST drives, a 20-character alphanumeric string printed on
# the drive label next to a QR code (which I gather is supposed to represent
# the same string). There is no explanation (on the drive) of what this string
# is though.
#
# Also for self-encrypting drives, it is possible to set up encryption
# without a password, if encryption is not currently active. This I suppose
# permits ransomware to encrypt data on the drive. This attack still
# requires root access on the system. To prevent it, I gather one can
# initialize the encryption by running, I think:
#
# sedutil-cli --initialSetup PASSWORD /dev/sdX
#
# I haven't tried this to see if there are additional steps that are required.

# Write back cache may be disabled.
# Check with:
#
# smartctl -x /dev/sdX
#
# Use sdparm to enable as follows:
#
# sdparm --set=WCE /dev/sdX
#
# See also:
# https://serverfault.com/questions/857271/better-performance-when-hdd-write-cache-is-disabled-hgst-ultrastar-7k6000-and

sector_size=4096
if test "$1" = 512; then
  sector_size=512
  shift
fi

exec sg_format -F -P 0 -v --fmtpinfo=0 -s $sector_size "$@"
