#!/usr/bin/env python3

# Pushes current branch to a contributor's branch on github.
# The current branch must have format pr-123.
# Any arguments to the script are forwarded to git push (e.g., -f).

import urllib, json, sys, re, subprocess, os.path

sys.path[0:0] = [os.path.join(os.path.dirname(__file__), '../lib/python')]

import github

branch = github.get_current_branch()
pr_num = github.get_current_pr_num()
origin = github.get_upstream_remote_name()
remote_url = github.get_remote_push_url(origin)
upstream_owner_name, upstream_repo_name = github.split_github_url(remote_url)
pr_owner_name, pr_repo_name, pr_branch = github.get_pr_info(
    upstream_owner_name, upstream_repo_name, pr_num)

if pr_owner_name not in github.get_remote_names():
    #subprocess.check_call(['git', 'remote', 'add', pr_owner_name, 'https://github.com/%s/%s' % (pr_owner_name, pr_repo_name)])
    subprocess.check_call(['git', 'remote', 'add', pr_owner_name, 'git@github.com:%s/%s' % (pr_owner_name, pr_repo_name)])

args = ['git', 'push', pr_owner_name, 'HEAD:%s' % pr_branch] + sys.argv[1:]
print("Execute: " + ' '.join(args))
subprocess.check_call(args)
