#!/bin/sh

set -e

mkdir -p "$HOME"/bin
if test -x /usr/sbin/pm-suspend; then
  ln -sf /usr/sbin/pm-suspend "$HOME"/bin/pm-suspend
fi

if ! test -f $HOME/.xscreensaver; then
  ln -s apps/pubfiles/home/xscreensaver $HOME/.xscreensaver
fi

if ! test -f $HOME/.xinitrc; then
  cp home/xinitrc $HOME/.xinitrc
fi
