#!/bin/sh

# https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

set -e

sudo apt-get install \
     apt-transport-https \
     ca-certificates

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-6.x.list

sudo apt-get update
sudo apt-get install elasticsearch
