#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo sh -x "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

if echo "$0" |grep -q /; then
  BASE=`dirname "$0"`
else
  echo "Cannot determine base directory" 1>&2
  exit 2
fi

. $BASE/common.sh

echo Installing for:
echo Headful: `is_headful; yesno $?`
echo Multimedia: `install_mm; yesno $?`

install_sources() {
  sources_list_src="$1"
  sources_list_dest=/etc/apt/sources.list
  if ! test -e $sources_list_dest; then
    install -m 644 $sources_list_src $sources_list_dest
    apt-get update
  elif ! diff -q $sources_list_src /etc/apt/sources.list; then
    backup_path=$sources_list_dest.`date +%Y%m%d`
    if test -e $backup_path; then
      echo $backup_path already exists, aborting 1>&2
      exit 2
    fi
    mv /etc/apt/sources.list $backup_path
    install -m 644 $sources_list_src $sources_list_dest
    apt-get update
  fi
}

if is_devuan; then
 install_sources $BASE/../config/apt/devuan/sources.list
elif is_debian; then
 install_sources $BASE/../config/apt/debian/sources.list
fi

install_if_needed \
  openntpd smartmontools openssh-server \
  zsh sudo man-db dnsutils \
  git curl make gcc \
  zip unzip net-tools rsync python-pip tmux

if is_headful; then
  install_if_needed \
    gitk libvte9 scite feh \
    firefox-esr xpdf evince chromium \
    xinit xauth openbox xscreensaver \
    xfonts-terminus

  if install_mm; then
    install_if_needed mplayer alsa-utils youtube-dl
  fi
fi

if lspci -v|grep iwlwifi; then
  install_if_needed firmware-iwlwifi
fi

echo '%sudo ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/sudo-group
chmod 0400 /etc/sudoers.d/sudo-group

install_if_needed nvi
update-alternatives --set editor /usr/bin/nvi
update-alternatives --set vi /usr/bin/nvi

chsh -s /bin/zsh root
if test "`id -u`" = 0 && test -n "$SUDO_USER"; then
  user=$SUDO_USER
elif test "`id -u`" != 0; then
  chsh -s /bin/zsh `id -un`
fi

if have_user me; then
  chsh -s /bin/zsh me
  usermod -a -G sudo me
fi

if have_user w; then
  chsh -s /bin/zsh w
fi

if is_laptop; then
  install_if_needed \
    acpi pm-utils hdparm wireless-tools wpasupplicant \
    nfs-common

  if lspci |grep -q 'Intel.*PRO/Wireless.*AGN'; then
    install_if_needed firmware-iwlwifi
  fi

  if ! grep -q '^apm = 255' /etc/hdparm.conf; then
    sed -i -e s/'^apm =/#apm =/' /etc/hdparm.conf
    echo apm = 255 |tee -a /etc/hdparm.conf
  fi
fi

# disable beep
# https://linuxconfig.org/turn-off-beep-bell-on-linux-terminal
echo 'blacklist pcspkr' >> /etc/modprobe.d/blacklist.conf

"$(dirname $0)"/disable-lid-suspend

if test -f /usr/bin/gtkterm2; then
  update-alternatives --set x-terminal-emulator /usr/bin/gtkterm2
fi
