#!/bin/sh

# http://www.pvv.ntnu.no/~knuta/xmms/

set -e

(
  echo 'deb [allow-insecure=yes] http://www.pvv.ntnu.no/~knuta/xmms/squeeze ./'
  echo 'deb-src [allow-insecure=yes] http://www.pvv.ntnu.no/~knuta/xmms/squeeze ./'
) |sudo tee /etc/apt/sources.list.d/xmms.list

sudo apt-get update
sudo apt-get install xmms

# Unsigned repo installs:
# https://askubuntu.com/questions/732985/force-update-from-unsigned-repository-ubuntu-16-04#732987
#
# sudo apt -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true update
