#!/bin/sh

set -e

if which curl >/dev/null 2>/dev/null; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
else
  wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
fi
