#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

# 3.2
#apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
# 3.6
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
# 4.0
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
# 4.2
curl -sfL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -

relname=`lsb_release -sc`

#echo "deb http://repo.mongodb.org/apt/debian $relname/mongodb-org/3.2 main" | tee /etc/apt/sources.list.d/mongodb-org.list
#echo "deb http://repo.mongodb.org/apt/debian $relname/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org.list
#echo "deb http://repo.mongodb.org/apt/debian $relname/mongodb-org/4.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org.list
echo "deb http://repo.mongodb.org/apt/debian $relname/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d/mongodb-org.list

apt-get update
apt-get install mongodb-org
