#!/bin/sh

# IMPORTANT: this installation writes into current working directory.
# Maybe it does more undesirable nonsense.
# Do not use from a trusted user account.

set -e

if test `id -u` = 0; then
  echo This script should not be run as root 1>&2
  exit 1
fi

if test `whoami` = me; then
  echo This script should not be run as me 1>&2
  exit 1
fi

echo 'prefix = ${HOME}/.npm-root' >$HOME/.npmrc

if ! $HOME/bin/yarn -v; then
  if ! $HOME/bin/npm -v; then
    curl https://www.npmjs.com/install.sh |bash
  fi

  $HOME/.npm-root/bin/npm install -g yarn
fi

mkdir -p $HOME/bin

cd $HOME/bin

for f in $HOME/.npm-root/bin/*; do
  ln -sf "$f"
done
