#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo sh -x "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

if echo "$0" |grep -q /; then
  BASE=`dirname "$0"`/..
else
  echo "Cannot determine base directory" 1>&2
  exit 2
fi

. $BASE/common.sh

install_if_needed python3-daemonize

mkdir -p /usr/libexec/pubfiles

install -m 555 -t /usr/libexec/pubfiles -o root -g root "$BASE"/script/connect-wireless
install -m 444 -t /usr/libexec/pubfiles -o root -g root "$BASE"/script/common.sh
if test -d /etc/pm/sleep.d; then
  install -m 555 -t /etc/pm/sleep.d -o root -g root "$BASE"/config/pm/sleep.d/wireless_resume
else
  echo /etc/pm/sleep.d missing - not a laptop? - skipping resume configuration
fi
install -m 555 -t /etc/boot.d -o root -g root "$BASE"/config/boot.d/wireless-auto-connect
