#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

apt-get install \
  acpi pm-utils hdparm \
  youtube-dl mplayer alsa-utils feh \
  nfs-client

if lspci |grep -q 'Intel.*PRO/Wireless.*AGN'; then
  apt-get install firmware-iwlwifi
fi

if ! grep -q '^apm = 255' /etc/hdparm.conf; then
  sed -i -e s/'^apm =/#apm =/' /etc/hdparm.conf
  echo apm = 255 |tee -a /etc/hdparm.conf
fi
