#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

apt-get install \
  zsh sudo man-db openssh-server smartmontools \
  gitk curl make \
  libvte9 scite \
  firefox-esr xpdf evince \
  xinit xauth openbox xscreensaver \
  xfonts-terminus \
  zip unzip

install_mm=true
if grep -q 'Intel.*7700K' /proc/cpuinfo; then
  install_mm=false
fi

if $install_mm; then
  apt-get install mplayer alsa-utils
fi

echo '%sudo ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/sudo-group
chmod 0400 /etc/sudoers.d/sudo-group

apt-get install nvi
update-alternatives --set editor /usr/bin/nvi

chsh -s /bin/zsh root
chsh -s /bin/zsh me
if id w >/dev/null 2>&1; then
  chsh -s /bin/zsh w
fi

usermod -a -G sudo me
