#!/bin/sh

# It seems debian now packages up-to-date docker as docker.io,
# one could also just install docker-compose.

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/

set -e

sudo apt-get install \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common \
  lsb-release

id=$(. /etc/os-release; echo "$ID" |sed -e s/devuan/debian/)
release=$(lsb_release -cs |sed -e s/bullseye/buster/ -e s/ascii/stretch/ -e 's/excalibur ceres/bookworm/' -e s,n/a,buster,)

curl -fsSL https://download.docker.com/linux/$id/gpg | sudo apt-key add -

sudo rm -f /etc/apt/sources.list.d/docker.list

if false; then
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
fi

echo "deb https://download.docker.com/linux/$id \
   $release \
   stable" |sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update

# Removes docker.io, possibly docker-cli on newer systems?
sudo apt-get install docker-ce docker-ce-cli docker-buildx-plugin

# For some reason /etc/init.d/docker is not executable
chmod +x /etc/init.d/docker

sudo groupmod docker || sudo groupadd docker

if id w >/dev/null 2>/dev/null; then
	sudo usermod -aG docker w
fi

sudo apt install docker-compose

if test -f /etc/init.d/docker; then
	sudo /etc/init.d/docker start
fi
