#!/bin/sh

set -e

mkdir -p $HOME/bin

if which curl >/dev/null 2>/dev/null; then
  curl -o $HOME/bin/m https://raw.githubusercontent.com/aheckmann/m/master/bin/m
else
  wget -qO- $HOME/bin/m https://raw.githubusercontent.com/aheckmann/m/master/bin/m
fi

chmod +x $HOME/bin/m
