#!/bin/sh

set -e

if test -d ~/.rbenv; then
  (cd ~/.rbenv && git pull)
else
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if test -d ~/.rbenv/plugins/ruby-build; then
  (cd ~/.rbenv/plugins/ruby-build && git pull)
else
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

sudo apt-get install gcc
