#!/usr/bin/env ruby

require 'combine_pdf'

if ARGV.empty?
  files = Dir['*.pdf'].sort
else
  files = ARGV
end

out = CombinePDF.new
front = CombinePDF.load(files.first)
back = CombinePDF.load(files.last)

if front.pages.length != back.pages.length
  raise "Front #{front.pages.length} pages, back #{back.pages.length} pages"
end

# Interleave pages assuming the back pages are in reverse order
front.pages.each_with_index do |f, i|
  b = back.pages[back.pages.length-1-i]

  out << f
  out << b
end

if files.first =~ /-p1\.pdf\z/
  out_fn = files.first.sub(/-p1\.pdf\z/, '.pdf')
else
  out_fn = 'out.pdf'
end

if files.include?(out_fn)
  raise "Refusing to overwrite #{out_fn}"
end

out.save(out_fn)
