#!/usr/bin/env ruby

# https://peter.sh/experiments/chromium-command-line-switches/
# https://superuser.com/questions/1343290/disable-chrome-session-restore-popup

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: launch-chromium [-u user] profile"

  opts.on("-u", "--user USER", "Launch as given user") do |v|
    options[:user] = v
  end

  opts.on("-e", "--ext PATH", "Load unpacked extension at PATH") do |v|
    options[:extensions] ||= []
    options[:extensions] << v
  end

  opts.on("-E", "--exist-ext PATH", "Load unpacked extension at PATH if it exists") do |v|
    if File.directory?(v)
      options[:extensions] ||= []
      options[:extensions] << v
    end
  end
end.parse!

profile, = ARGV

if profile.nil?
  raise "Usage: launch-chromium [-u user] profile"
end

target_user_slug = options[:user] || profile
target_user = if target_user_slug.start_with?('br-')
  target_user_slug
else
  target_user = "br-#{target_user_slug}"
end

target_xauthority_path = "/home/#{target_user}/.Xauthority"
puts `xauth list | sed -e 's/^/add /' | sudo -u "#{target_user}" env HOME=/home/"#{target_user}" XAUTHORITY=#{target_xauthority_path} xauth`

profile_arg = if profile == target_user_slug
  profile_base = "/home/#{target_user}"
  ''
else
  profile_base = "/home/#{target_user}/#{profile}"
  "HOME=#{profile_base} XDG_HOME=#{profile_base}"
end

extension_arg = if options[:extensions]
  "--load-extension=#{options[:extensions].join(',')}"
else
  ''
end

puts `sudo -u #{target_user} #{File.dirname(File.realpath($0))}/../home/chromium/install #{profile_base}`

exec("sudo -u #{target_user} env #{profile_arg} DISPLAY=#{ENV.fetch('DISPLAY')} XAUTHORITY=#{target_xauthority_path} chromium --disable-notifications --disable-smooth-scrolling --disable-sync --disable-session-crashed-bubble #{extension_arg}")
