#!/usr/bin/env ruby

# https://peter.sh/experiments/chromium-command-line-switches/
# https://superuser.com/questions/1343290/disable-chrome-session-restore-popup

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: launch-chromium [-u user] profile"

  opts.on("-n", "--new", "Assume a fresh launch") do
    options[:new] = true
  end

  opts.on("-u", "--user USER", "Launch as given user") do |v|
    options[:user] = v
  end

  opts.on("-e", "--ext PATH", "Load unpacked extension at PATH") do |v|
    options[:extensions] ||= []
    options[:extensions] << v
  end

  opts.on("-E", "--exist-ext PATH", "Load unpacked extension at PATH if it exists") do |v|
    if File.directory?(v)
      options[:extensions] ||= []
      options[:extensions] << v
    end
  end
end.parse!

profile, *args = ARGV

if profile.nil?
  raise "Usage: launch-chromium [-u user] profile"
end

target_user_slug = options[:user] || profile
target_user = if target_user_slug.start_with?('br-')
  target_user_slug
else
  target_user = "br-#{target_user_slug}"
end

target_xauthority_path = "/home/#{target_user}/.Xauthority"
puts `xauth list | sed -e 's/^/add /' | sudo -u "#{target_user}" env HOME=/home/"#{target_user}" XAUTHORITY=#{target_xauthority_path} xauth`

profile_arg = if profile == target_user_slug
  profile_base = "/home/#{target_user}"
  ''
else
  profile_base = "/home/#{target_user}/#{profile}"
  "HOME=#{profile_base} XDG_HOME=#{profile_base}"
end

extension_arg = if options[:extensions]
  "--load-extension=#{options[:extensions].join(',')}"
else
  ''
end

install_args = ''
if options[:new]
  install_args << " -n"
end
puts `sudo -u #{target_user} #{File.dirname(File.realpath($0))}/../home/chromium/install #{profile_base} #{install_args}`

chromium_bin = nil
%w(chromium chrome).each do |bn|
  ENV.fetch('PATH').split(':').each do |dn|
    if File.exist?(path = File.join(dn, bn))
      chromium_bin = path
      break
    end
  end
  break if chromium_bin
end

if chromium_bin.nil?
  raise "chromium or chrome not found in PATH"
end

# Resolve local symlinks so that the binary can be spawned via sudo.
chromium_bin = File.realpath(chromium_bin)

# TODO properly escape args or redo this entire invocation
cmd = "sudo -u #{target_user} env #{profile_arg} DISPLAY=#{ENV.fetch('DISPLAY')} XAUTHORITY=#{target_xauthority_path} #{chromium_bin} --disable-notifications --disable-smooth-scrolling --disable-sync --disable-session-crashed-bubble --disable-gaia-services #{extension_arg} #{args.join(' ')}"
puts cmd
exec(cmd)
