#!/bin/sh

# Permissions:
# https://unix.stackexchange.com/questions/326883/owner-of-sshfs-mounted-directory-with-777-permission-cant-open-it-no-acl-no-s
# sshfs -o allow_other,default_permissions mike@192.0.2.0:/home/mike moo

set -e

src="$1"
dest="$2"

if test -z "$src"; then
  echo "Usage: mount-ssh src [dest]" 1>&2
  exit 1
fi

if test -z "$dest"; then
  if echo "$src" |egrep -q ':$'; then
    src=`echo "$src" |tr -d :`
  fi
  if echo "$src" |egrep -q '[/]'; then
    echo "Bad source spec when no destination given; must be a hostname only" 1>&2
    exit 1
  fi
  dest="/mnt/`id -un`/$src"
  src="$src":
fi

mkdir -p "$dest"
sshfs "$src" "$dest"
