#!/bin/sh

set -e

prefix=false

while getopts p opt; do
  case $opt in
  p)
    prefix=true
    ;;
  *)
    echo "Bogus option $opt" 1>&2
    exit 1
    ;;
  esac
done
shift $((OPTIND-1))

device="$1"
dest="$2"

if test -z "$device" || (! $prefix && test -z "$dest"); then
  echo "Usage: mount-luks device destination" 1>&2
  echo "       mount-luks -p device [prefix]" 1>&2
  exit 1
fi

original_device="$device"
if ! echo "$device" |grep -Eq '[0-9]$'; then
  device="$device"1
fi

if ! echo "$device" |fgrep -q /; then
  device="/dev/$device"
fi

if test "$device" != "$original_device"; then
  echo "Adjusted device from $original_device to $device" 1>&2
fi

if ! $prefix; then
  original_dest="$dest"
  if ! echo "$dest" |fgrep -q /; then
    dest="/mnt/$dest"
  fi
fi

if test "$dest" != "$original_dest"; then
  echo "Adjusted destination from $original_dest to $dest" 1>&2
fi

label=`blkid -o value -s LABEL "$device"`
if test -z "$label"; then
  echo "No label on $device, aborting" 1>&2
  exit 1
fi

# Set write-back cache because it seems to be getting cleared on its own.
# Is the setting not surviving power-off?
# Enabling the cache on e.g. /dev/sda1 does work the same as enabling it
# on /dev/sda, thus we can use a partition device here instead of the
# whole disk device.
sdparm --set=WCE "$device"

if test -e /dev/mapper/"$label"; then
  echo "luks already opened? skipping" 1>&2
else
  cryptsetup open "$device" "$label"
fi

if $prefix; then
  if test -z "$dest"; then
    dest=/mnt/disk
  fi
  dest="$dest/$label"
  echo "Using $dest as mount point" 1>&2
  mkdir -p "$dest"
fi

mount -o noatime,nodiratime /dev/mapper/"$label" "$dest"
