#!/bin/sh

set -e

if test "$1" = -u; then
  umount /mnt/tmp
  exit
fi

found_dev_name=
for path in /sys/block/sd*; do
  dev_name=`basename $path`
  
  if test `cat $path/removable` = 1; then
    if test -n "$found_dev_name"; then
      echo "Multiple removable devices: $dev_name, $found_dev_name" 1>&2
      exit 1
    fi
    
    if ! blkid /dev/$dev_name; then
      echo "blkid failed on $dev_name" 1&>2
      continue
    fi
    
    found_dev_name=$dev_name
  fi
done

if test -z "$found_dev_name"; then
  echo No removable devices 1>&2
  exit 1
fi

if test `ls /sys/block/$found_dev_name/*/partition |wc -l` != 1; then
  echo Multiple partitions on $found_dev_name 1>&2
fi

part_name=`basename $(dirname $(ls /sys/block/$found_dev_name/*/partition))`

user=
if test -f /etc/setup.conf; then
  user=`egrep ^main_user= /etc/setup.conf |cut -c 11-`
fi
if test -z "$user"; then
  if id me >/dev/null 2>&1; then
    user=me
  else
    echo 'Cannot determine user to use' 2>&1
    exit
  fi
fi

mount -o uid=$user,gid=$user /dev/$part_name /mnt/tmp
