#!/bin/sh

# If libreoffice-writer is not installed, soffice runs fine with the
# --writer switch and shows a format selector dialog which doesn't have any
# text editor-looking options, in some situations.
# Installing some dependencies of libreoffice-writer (but not writer itself)
# produces an error. Apparently some of those components get loaded and then
# fail to load writer.
# Libreoffice really is braindead in many ways.

set -e

if test -z "$1"; then
  echo "Usage: `basename $0` path" 1>&2
  exit 2
fi

name="$1"

if ! basename "$name" |fgrep .; then
  echo "Adjusting $name to $name.odt"
  name="$name.odt"
fi

if ! test -f "$name"; then
#  tmpdir=`mktemp -d`
#  echo x > $tmpdir/empty.txt
#  pandoc -t odt $tmpdir/empty.txt -o "$name"
  touch "$name"
fi

if ! which lowriter >/dev/null 2>&1; then
  echo 1>&2
  echo "WARNING: lowriter not in PATH - is libreoffice-writer installed?" 1>&2
  echo 1>&2
fi

soffice --writer --norestore "$name"
