#!/usr/bin/env ruby

# Workaround for https://github.com/npm/npm/issues/18940

require 'json'

class Runner
  def initialize(skip_lint: false)
    @skip_lint = skip_lint
  end
  
  def run(scripts, cmd)
    if scripts[cmd]
      tests = scripts[cmd].split('&&')
      tests.each do |test|
        test.strip!
        if test =~ /\Anpm run ([-\w]+)\z/
          if (command = $1) =~ /^lint\b/
            next
          end
          run(scripts, command)
        else
          rv = system(test)
          unless rv
            $stderr.puts("Command exited with code #{$?.exitstatus}: #{test}")
            exit 2
          end
        end
      end
    end
  end
end

if ARGV.first == '-t'
  ARGV.shift
  runner = Runner.new(skip_lint: true)
else
  runner = Runner.new
end

config = JSON.parse(File.read('package.json'))
if scripts = config['scripts']
  runner.run(scripts, 'test')
end
