#!/bin/sh

# Patches debuggers to not ask for confirmation on exit.
# byebug tracking issue: https://github.com/deivid-rodriguez/byebug/issues/404
# byebug proposed patch: https://github.com/deivid-rodriguez/byebug/pull/605

roots="$@"
if test -z "$1"; then
  candidates="$HOME/.rbenv $HOME/.cache/vendor/bundle"
  for p in $candidates; do
    if test -d $p; then
      roots="$roots $p"
    fi
  done
  if test -z "$roots"; then
    echo "No roots found - tried $candidates" 1>&2
    exit 2
  fi
fi

for root in $roots; do
  find "$root" -name quit.rb -path '*/byebug/*' -exec \
    sed -e '/quit.confirmations.really/d' -i {} \;

  # JRuby ruby-debug

  find "$root" -name quit.rb -path '*/ruby-debug/*' -exec \
    sed -e 's/confirm("Really quit.*")/true/' -i {} \;
    
  # debug
  find "$root" -name debug.rb -path '*/debug-*' -exec \
    sed -e 's/input = readline("Really quit? (y.n) ", false)/input = "y"/' -i {} \;
  find "$root" -name debug.rb -path '*/jruby-*' -exec \
    sed -e 's/input = readline("Really quit? (y.n) ", false)/input = "y"/' -i {} \;
  find "$root" -name session.rb -path '*/ruby/*' -exec \
    sed -e "s/if ask 'Really quit?'/if true/" -i {} \;
done
