#!/bin/sh

set -e

# https://www.reddit.com/r/openbsd/comments/ived5q/solved_a_few_issues_recording_sound_audio_using/

pulse=true

if $pulse; then
  backend=pulse
  device=`pacmd list-sources |grep name: |fgrep -v '.monitor>' |awk '{print $2}' |tr -d '<>'`
else
  backend=alsa
  device=hw:0
fi

ffmpeg  -video_size `xdpyinfo|grep dimensions:|head -1 |awk '{print $2}'` \
  -framerate 30 \
  -f x11grab -i :0.0+0,0 \
  -f $backend -ac 2 -i $device \
  -c:v libx264rgb -crf 0 -preset ultrafast -color_range 2 \
  -c:a pcm_s16le \
  "$@"
