#!/bin/sh

set -e

mixer=
rate=
video=false

while getopts admpr:v opt; do
  case $opt in
  a)
    mixer=alesis
    ;;
  m)
    mixer=m-audio
    ;;
  d)
    mixer=dl32r
    ;;
  p)
    mixer=presonus
    ;;
  r)
    rate="$OPTARG"
    ;;
  v)
    video=true
    ;;
  *)
    echo "Bogus option $opt" 1>&2
    exit 10
    ;;
  esac
done
shift $((OPTIND-1))

if test -z "$mixer"; then
  if fgrep -qx DL32R /proc/asound/card*/id; then
    mixer=dl32r
  elif fgrep -qx Pro /proc/asound/card*/id; then
    mixer=m-audio
  elif fgrep -qx 'AudioBox USB' /proc/asound/card*/midi0; then
    mixer=presonus
  fi
  
  if test -n "$mixer"; then
    echo "Detected mixer: $mixer"
  else
    echo "Mixer not specified and not detected" 1>&2
  fi
fi

if test -z "$rate"; then
  rate=48000
fi

arecord -l
echo
echo ---
echo

ffmpeg='ffmpeg -hide_banner'

find_card() {
  id="$1"
  filename="${2:-id}"
  for f in /proc/asound/card*/"$filename"; do
    if fgrep -qx "$id" $f; then
      card=`basename $(dirname $f) |sed -e s/card//`
      echo "$card"
      return 0
    fi
  done
  return 1
}

video_input=
video_processing=

if $video; then
  video_input="-video_size `xdpyinfo|grep dimensions:|head -1 |awk '{print $2}'` \
    -framerate 30 \
    -f x11grab -i :0.0+0,0"
  video_processing="-c:v libx264rgb -crf 0 -preset ultrafast -color_range 2"
fi

case "$mixer" in
alesis)
  # 44100 & 48000 sample rates are supported.
  eval $ffmpeg $video_input -f alsa -sample_rate "$rate" -i hw:1 \
    $video_processing "$@"
  ;;
m-audio)
  card=`find_card Pro || echo 1`
  # 44100 & 48000 sample rates are supported.
  eval $ffmpeg $video_input -f alsa -sample_rate "$rate" -i hw:$card \
    $video_processing "$@"
  ;;
dl32r)
  card=`find_card DL32R || echo 1`
  eval $ffmpeg $video_input \
    -c:a pcm_s32le -f alsa -sample_rate "$rate" -channels 32  -i hw:$card \
    $video_processing -c:a copy "$@"
  ;;
presonus)
  card=`find_card 'AudioBox USB' midi0 || echo 1`
  eval $ffmpeg $video_input \
    -c:a pcm_s24le -f alsa -sample_rate "$rate" -i hw:$card \
    $video_processing -c:a copy "$@"
  ;;
*)
  echo "Bogus mixer $mixer" 1>&2
  exit 2
  ;;
esac
