#!/bin/sh

set -e

mixer=
rate=

while getopts admr: opt; do
  case $opt in
  a)
    mixer=alesis
    ;;
  m)
    mixer=m-audio
    ;;
  d)
    mixer=dl32r
    ;;
  r)
    rate="$OPTARG"
    ;;
  *)
    echo "Bogus option $opt" 1>&2
    exit 10
    ;;
  esac
done
shift $((OPTIND-1))

if test -z "$mixer"; then
  if fgrep -qx DL32R /proc/asound/card*/id; then
    mixer=dl32r
  elif fgrep -qx Pro /proc/asound/card*/id; then
    mixer=m-audio
  fi
fi

if test -z "$rate"; then
  rate=48000
fi

arecord -l
echo
echo ---
echo

ffmpeg='ffmpeg -hide_banner'

id2card() {
  id="$1"
  for f in /proc/asound/card*/id; do
    if fgrep -qx "$id" $f; then
      card=`basename $(dirname $f) |sed -e s/card//`
      echo "$card"
      return 0
    fi
  done
  return 1
}

case "$mixer" in
alesis)
  # 44100 & 48000 sample rates are supported.
  eval $ffmpeg -f alsa -sample_rate "$rate" -i hw:1 "$@"
  ;;
m-audio)
  card=`id2card Pro || echo 1`
  # 44100 & 48000 sample rates are supported.
  eval $ffmpeg -f alsa -sample_rate "$rate" -i hw:$card "$@"
  ;;
dl32r)
  card=`id2card DL32R || echo 1`
  eval $ffmpeg \
    -c:a pcm_s32le -f alsa -sample_rate "$rate" -channels 32  -i hw:1 \
    -c copy "$@"
  ;;
*)
  echo "Bogus mixer $mixer" 1>&2
  exit 2
  ;;
esac
