#!/bin/sh

set -e

apt-get remove \
    gitk libvte9 feh \
    evince gimp \
    xinit xauth openbox xsecurelock xss-lock xautolock \
    x11-xserver-utils x11-utils xserver-xorg \
    xfonts-terminus fonts-terminus-otb libnss3-tools libglib2.0-bin \
    ruby-slim \
    xpdf \
    scite \
    mpv alsa-utils yt-dlp mplayer \
    firefox firefox-esr

apt-get autoremove
