#!/usr/bin/env ruby

require 'addressable'
require 'nokogiri'

def process_content(content)
  fix_url(content)
end

def fix_url(url)
  if url.start_with?('https://www.google.com/url')
    url = Addressable::URI.parse(url)
    q = url.query_values.fetch('q')
    q
  else
    url
  end
end

def process_stream(io)
  doc = Nokogiri::HTML(io)
  doc.xpath('//a').each do |a|
    href = a.attr('href')
    if href
      fixed_href = fix_url(href)
      if href != fixed_href
        a.set_attribute('href', fixed_href)
      end
    end
  end
  doc.to_s
end

def process_file(path)
  out = File.open(path) do |f|
    process_stream(f)
  end
  File.open(path, 'w') do |f|
    f << out
  end
end

if ARGV.any?
  ARGV.each do |path|
    if File.exist?(path)
      process_file(path)
    elsif path =~ /^https?:/
      puts process_content(path)
    else
      raise "Unknown argument or file does not exist: #{path}"
    end
  end
else
  process_stream(STDIN)
end
