#!/usr/bin/env ruby

autoload :FileUtils, 'fileutils'
autoload :Find, 'find'
autoload :OptionParser, 'optparse'
require_relative '../lib/ruby/fs_helpers'

class RendererBase
  def render_path(markdown_path)
    render_text(File.read(markdown_path))
  end
end

class RedcarpetRenderer < RendererBase
  def initialize
    require 'redcarpet'
  end

  def render_text(text)
    markdown.render(text)
  end

  def markdown
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      autolink: true, tables: true)
  end
end

class PandocRenderer < RendererBase
  def initialize
  end

  def render_path(markdown_path)
    cmd = ['pandoc', markdown_path]
    rd, wr = IO.pipe
    pid = Process.spawn(*cmd, out: wr)
    wr.close
    output = rd.read
    Process.waitpid(pid)
    output
  end
end

class PostProcessor
  def initialize
    require 'nokogiri'
  end

  def process(text)
    doc = Nokogiri::HTML(text)
    doc.xpath('//h1').each do |h1|
      p h1.text
    end
    doc.to_s
  end
end

class Runner
  include FsHelpers

  def initialize(**opts)
    @options = opts
  end

  attr_reader :options

  def root
    options.fetch(:root)
  end

  alias :start_path :root

  def output_root
    options.fetch(:output_path)
  end

  def run
    Find.find(root) do |path|
      next if File.directory?(path)

      if File.extname(path) == '.md'
        render_markdown(path)
      else
        dest = File.join(output_root, relativize(path))
        FileUtils.mkdir_p(File.dirname(dest))
        FileUtils.cp(path, dest)
      end
    end
  end

  private

  def render_markdown(path)
    out_path = File.join(output_root, relativize(path).sub(/\.md/, '.html'))
    rendered = renderer.render_path(path)
    rendered = "<!doctype html><html><head><meta charset='utf-8'></head><body>#{rendered}</body></html>"
    rendered = postprocessor.process(rendered)
    FileUtils.mkdir_p(File.dirname(out_path))
    File.open(out_path, 'w') do |f|
      f << rendered
    end
  end

  def renderer_class
    @renderer_class ||= begin
      Object.const_get((options[:renderer] || 'pandoc').sub(/./) { |m| m.upcase } + 'Renderer')
    end
  end

  def renderer
    @renderer ||= renderer_class.new
  end

  def postprocessor
    @postprocessor ||= PostProcessor.new
  end
end

options = {
}
OptionParser.new do |opts|
  opts.banner = "Usage: render-markdown-tree [options]"

  opts.on('-w', '--write PATH', 'Specify output directory') do |v|
    options[:output_path] = v
  end

end.parse!

path = ARGV.first
if path.nil?
  raise 'Usage'
end

Runner.new(root: path, **options).run
