#!/usr/bin/env python

CONFIG_FILE = '/etc/default/grub'

import re, subprocess

out = ''

with open(CONFIG_FILE) as f:
    with open(CONFIG_FILE + '.bak', 'w') as fb:
        fb.write(f.read())

with open(CONFIG_FILE) as f:
    for line in f.readlines():
        match = re.match(r'(\s*)GRUB_CMDLINE_LINUX="(.*)"$', line)
        if match:
            args = re.split(r'\s+', match.group(2))
            # python silliness when splitting an empty string
            if args == ['']:
                args = []
            if 'net.ifnames=0' not in args:
                args.append('net.ifnames=0')
            if 'biosdevname=0' not in args:
                args.append('biosdevname=0')
            line = match.group(1) + 'GRUB_CMDLINE_LINUX="%s"\n' % ' '.join(args)
        out += line
    
with open(CONFIG_FILE, 'w') as f:
    f.write(out)

subprocess.check_call(['update-grub'])
