#!/bin/sh

set -e

user="$1"
shift
if test -z "$user"; then
  echo "Usage: `basename $0` user command args..." 1>&2
  exit 1
fi

xrun() {
  sudo -Hu "$user" env XAUTHORITY=/home/"$user"/.Xauthority "$@"
}

exrun() {
  exec sudo -iHu "$user" env XAUTHORITY=/home/"$user"/.Xauthority "$@"
}

if ! xrun xdpyinfo; then
  xauth list |sed -e 's/^/add /' \
    |xrun xauth
fi

if ! xrun xdpyinfo; then
  echo "Failed to get access to invoking user's X session" 1>&2
  exit 2
fi

exrun "$@"
