#!/bin/sh

set -e

if test "`id -u`" != 0; then
  if which sudo 2>/dev/null 1>&2; then
    echo "This needs to be run as root, trying sudo" 1>&2
    exec sudo sh -x "$0" "$@"
  else
    echo "This needs to be run as root" 1>&2
    exit 2
  fi
fi

if ! id cr-fb; then
  useradd -m -s /usr/bin/zsh -u 2518 cr-fb
  echo 'export XAUTHORITY=$HOME/.Xauthority' |sudo -u cr-fb tee /home/cr-fb/.Xauthority
fi

if id me; then
  echo 'me ALL = (cr-fb) NOPASSWD: ALL' >/etc/sudoers.d/me-cr-fb
  sudo -u me xauth list | sed -e 's/^/add /' | sudo -u cr-fb env HOME=/home/cr-fb XAUTHORITY=/home/cr-fb/.Xauthority xauth
fi
