#!/bin/sh

set -e

exec `dirname "$0"`/setup-cr w 2516 w

if id w; then
  usermod -G cr-w w
fi

if id me; then
  echo 'me ALL = (cr-w) NOPASSWD: ALL' >/etc/sudoers.d/me-cr-w
  #sudo -u me xauth list | sed -e 's/^/add /' | sudo -u cr-w env HOME=/home/cr-w XAUTHORITY=$xauthority_path xauth
fi
