#!/bin/sh

set -e

. /etc/setup.conf

if id me; then
  `dirname "$0"`/setup-br-sandbox-me
elif id w && test "$main_user" = w; then
  exec `dirname "$0"`/setup-br sandbox 2523 w
else
  echo 'Not handled' 1>&2
  exit 2
fi
