#!/usr/bin/env ruby

require_relative '../lib/ruby/child_process_facade'

if ARGV.empty?
  raise "Usage: sg_stop device..."
end

error = false
threads = ARGV.map do |device|
  if device =~ /\A\w+\z/
    device = "/dev/#{device}"
  end

  unless File.exist?(device)
    warn "Device does not exist: #{device}"
    error = true
  end

  Thread.new do
    # TODO do not sync if the drive is already spun down
    ChildProcessFacade.check_call(['sg_sync', device])
    # 3 seconds is definitely not enough, disk is spun back up
    sleep 5

    ChildProcessFacade.check_call(['sg_start', '-rS', device])

    # Check if the drive is really spun down
    # TODO Verify sdparm is installed before invoking it, and
    # eat the output.
    #ChildProcessFacade.uncheck_call(['sdparm', '-C', 'ready', device])
  end.tap do |thread|
    thread.name = device
  end
end

threads.each do |thread|
  begin
    thread.join
  rescue => exc
    puts "#{thread.name}: error: #{exc.class}: #{exc}"
    error = true
  end
end

exit(error ? 1 : 0)
