#!/bin/sh

set -e

device="$1"
if test -z "$device"; then
  echo "Usage: smart-report device" 1>&2
  exit 1
fi

sn=`smartctl -a "$device" |grep "^Serial Number:" |awk '{print $3}'`
echo "$sn"

smartctl -a "$device" >$sn.txt || true

smartctl -x "$device" >${sn}-x.txt || true
