#!/usr/bin/env ruby

require 'logger'
require 'optparse'
require 'yamaha'
require 'seriamp'

class Runner
  def run
    options = {}
    OptionParser.new do |opts|
      opts.banner = "Usage: sonamp-auto-off [-l log-path] [-D]"

      opts.on("--daemonize", "-D", "Daemonize") do
        options[:daemonize] = true
      end

      opts.on("--log=PATH", "-l", "Path to log file") do |path|
        options[:log_path] = path
      end

    end.parse!

    @options = options.freeze

    if options[:daemonize]
      Process.daemonize
    end

    bump('application start')

    prev_sonamp_power = nil
    handle_exceptions do
      prev_sonamp_power = sonamp_client.get_zone_power.values.any? { |v| v == true }
    end

    loop do
      sonamp_power = nil
      handle_exceptions do
        sonamp_power = sonamp_client.get_zone_power.values.any? { |v| v == true }
        if sonamp_power && prev_sonamp_power == false
          bump('amplifier turned on')
        end
        prev_sonamp_power = sonamp_power
      end

      # If we cannot query the receiver, assume it is on to prevent unintended
      # turn-offs.
      receiver_power = nil
      handle_exceptions do
        receiver_power = yamaha_client.main_power
      end
      p receiver_power
      case receiver_power
      when true
        bump('receiver is on')
        if sonamp_power == false
          puts("turning on amplifier")
          sonamp_client.set_zone_power(1, true)
          sonamp_client.set_zone_power(2, true)
          sonamp_client.set_zone_power(3, true)
        end
      when nil
        bump('failed to communicate with receiver - assuming it is on')
      end

      if @alive_through < monotonic_time
        logger.info("Turning amplifier off")
        handle_exceptions do
          sonamp_client.power_off
        end
      else
        delta = (@alive_through - monotonic_time).to_i
        puts "TTL: #{delta / 60}:#{'%02d' % (delta % 60)}"
      end

      sleep 20
    end
  end

  attr_reader :options

  private

  def handle_exceptions
    yield
  rescue Interrupt, SystemExit, NoMemoryError
    raise
  rescue => exc
    logger.warn("Unhandled exception: #{exc.class}: #{exc}")
  end

  def bump(reason)
    logger.debug("Bumping 7 minutes: #{reason}")
    @alive_through = monotonic_time + 7*60
  end

  def sonamp_client
    @sonamp_client ||= Seriamp::Sonamp::AutoClient.new(logger: Logger.new(log_stream, progname: 'sonamp'))
  end

  def yamaha_client
    @yamaha_client ||= Seriamp::Yamaha::AutoClient.new(logger: Logger.new(log_stream, progname: 'yamaha'))
  end

  def log_stream
    @log_stream ||= if path = options[:log_path]
      File.open(path, 'a')
    else
      STDERR
    end
  end

  def logger
    @logger ||= begin
      Logger.new(log_stream, progname: 'main')
    end
  end

  def monotonic_time
    Process.clock_gettime(Process::CLOCK_MONOTONIC)
  end
end

Runner.new.run
