#!/bin/sh

set -e

# Put a node_modules subdir in the path.
# Without it webpack's detection of installed packages (GTFO)
# is broken.

bn=`pwd |sha1sum |awk '{print $1}'`
path=$HOME/.node_modules/$bn/node_modules

mkdir -p $path
rm -f node_modules
ln -s $path node_modules
