#!/bin/sh

set -x

if test -z "$1"; then
  echo "Usage: wg url" 1>&2
  exit 2
fi

url="$1"

if echo "$url" |grep -q "^https://pdf1.alldatasheet.com/pdfjsview/web/viewer.html?file=//"; then
  url=`echo "$url" |sed -e s,'^https://pdf1.alldatasheet.com/pdfjsview/web/viewer.html?file=//,https://,'`
fi

if echo "$url" |grep -q "^pdf1.alldatasheet.com/datasheet/pdf"; then
  url="https://$url"
fi

bn="`basename $url`"

curl -kLH User-Agent:Mozilla/5.0 -Haccept-language:en -o "$bn" "$url"
