#!/usr/bin/env ruby

require_relative '../lib/ruby/system_config'
require 'erb'
require 'etc'

TEMPLATE = <<-EOT
<%= main_user %> ALL = (ardour) NOPASSWD: ALL
EOT

class Context
  def main_user
    SystemConfig.main_user
  end

  def _binding
    binding
  end
end

puts "Configuring ardour for #{SystemConfig.main_user}"

result = ERB.new(TEMPLATE).result(Context.new._binding)

File.open('/etc/sudoers.d/ardour', 'w') do |f|
  f << result
end

begin
  Etc.getpwnam('ardour')
rescue ArgumentError
  system("useradd -m -s /bin/zsh -G audio -u 2533 ardour")
end

text = <<-EOT
@audio - rtprio 95
@audio - memlock 409600
EOT

File.open('/etc/security/limits.d/audio.conf', 'w') do |f|
  f << text
end
